//include(":Someone")
//include(":byebyeSlashCommands")
//include(":EncryptDMs")

include(":LightShotRoulette")
include(":BetterSilentTyping")
include(":HighlightReplies")
include(":EditServersLocally")
include(":InvisibleMessages")
include(":StupidityDB")
include(":Base64")
include(":EditMessagesLocally")
include(":Vibrator")
include(":PluginRepo")
include(":KyzaMode")
include(":ThemeRepo")
//include(":0TestPlugin")
include(":Vibrator2")
include(":GoodPerson")
include(":StupitCase")
include(":Amog\u200C\u200Dus")
include(":ReviewDB")
include(":ServerReviews")
include(":EditEverything")
include(":DisableVerifyScreen")
include(":UpsideDownChat")
include(":ShuffleUsers")
include(":VoiceMessages")
include(":UserReviews")
//include(":Shortcuts")
//include(":FixTimestamps")

rootProject.name = "AliucordPlugins"
